FROM java:8-jre

RUN wget http://www-us.apache.org/dist/spark/spark-1.6.3/spark-1.6.3-bin-hadoop2.6.tgz && \
    tar zxf ./spark-1.6.3-bin-hadoop2.6.tgz && \
    rm -f ./spark-1.6.3-bin-hadoop2.6.tgz
